version: '3.9'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:latest   # Changed from mysql:5.7 to postgres:latest
    restart: always
    environment:
      POSTGRES_DB: draftbash  # Changed from MYSQL_DATABASE to POSTGRES_DB
      POSTGRES_USER: postgres # Changed from MYSQL_USER to POSTGRES_USER
      POSTGRES_PASSWORD: postgres # Changed from MYSQL_PASSWORD to POSTGRES_PASSWORD
    ports:
      - "5432:5432"            # Changed from 3306 to 5432 for PostgreSQL