version: '3.8'

services:
  postgres:
    image: postgres:16.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: draftbash
      POSTGRES_PASSWORD: devpassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
    command: ["postgres", "-c", "hba_file=/etc/postgresql/pg_hba.conf"]
    ports:
      - "5332:5432"

  app:
    build: .
    ports:
      - "3000:8080"
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: dev2

volumes:
  postgres-data: