# Common configurations applicable to all environments
spring:
  profiles:
    active: dev  # Set the default profile to 'dev'
  main:
    web-application-type: servlet

---

# Development profile configuration
spring:
  config:
    activate:
      on-profile: dev
  jwt:
    secret-key: myDevSecretKey
  flyway:
    baseline-on-migrate: true
    baseline-version: '0'
  datasource:
    url: jdbc:postgresql://0.0.0.0:5332/draftbash
    username: postgres
    password: devpassword

---

# Development profile configuration
spring:
  config:
    activate:
      on-profile: dev2
  jwt:
    secret-key: myDevSecretKey
  flyway:
    baseline-on-migrate: true
    baseline-version: '0'
  datasource:
    url: jdbc:postgresql://postgres:5432/draftbash
    username: postgres
    password: devpassword

---

# Production profile configuration
spring:
  config:
    activate:
      on-profile: prod
  jwt:
    secret-key: ${JWT_SECRET}
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: true