# Common configurations applicable to all environments
spring:
  profiles:
    active: dev  # Set the default profile to 'dev'
  main:
    web-application-type: servlet
  flyway:
    baseline-on-migrate: true
    baseline-version: '0'

logging:
  level:
    root: INFO

---

# Development profile configuration
server:
  port: 3000
spring:
  config:
    activate:
      on-profile: dev
  jwt:
    secret-key: json_web_token_secret_key_for_development_environment
  flyway:
    locations: classpath:db/migration,classpath:db/devmigration
  datasource:
    url: jdbc:postgresql://0.0.0.0:5332/draftbash
    username: postgres
    password: devpassword

---

# Another development profile configuration (dev2)
spring:
  config:
    activate:
      on-profile: dev2
  jwt:
    secret-key: json_web_token_secret_key_for_development_environment
  flyway:
    locations: classpath:db/migration,classpath:db/devmigration
  datasource:
    url: jdbc:postgresql://postgres:5432/draftbash
    username: postgres
    password: devpassword

---

# Production profile configuration
spring:
  config:
    activate:
      on-profile: prod
  jwt:
    secret-key: ${JWT_SECRET}
  flyway:
    locations: classpath:db/migration,classpath:db/devmigration
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: true