name: Continuous Deployment

on:
  push:
    paths:
      - 'backend/**'
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: "./backend"
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:latest

      - name: Deploy to EC2 Instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker stop app || true
            sudo docker rm app || true
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:latest
            sudo docker run -d --name app -p 80:8080 \
              -e SPRING_PROFILES_ACTIVE=prod \
              -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
              -e DATASOURCE_URL=${{ secrets.DATASOURCE_URL }} \
              -e DATASOURCE_USERNAME=${{ secrets.DATASOURCE_USERNAME }} \
              -e DATASOURCE_PASSWORD=${{ secrets.DATASOURCE_PASSWORD }} \
              ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:latest