on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Docker and Run Container on EC2 instance
      run: |
        # Install Docker
        sudo apt-get update
        sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        sudo apt-get update
        sudo apt-get install -y docker-ce

        # SSH into EC2 and run Docker container
        echo "$EC2_SSH_KEY" > key.pem
        chmod 600 key.pem
        ssh -i key.pem ubuntu@ec2-3-144-169-40.us-east-2.compute.amazonaws.com 'docker run -d -p 80:3000 sfeddes/draftbash:users-api'
      env:
        EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}