name: Continuous Integration

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build-lint-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Grant execute permission to gradlew
      run: chmod +x ./gradlew

    - name: Build Docker image
      run: docker build -t image-name .
    
    - name: Run Linter in Docker container
      run: |
        docker run image-name ./gradlew checkstyleMain checkstyleTest