name: Continuous Integration

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    name: Linting Checkstyle
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'
      
    - name: Grant execute permission to gradlew
      run: chmod +x ./gradlew

    - name: Clean build
      run: ./gradlew clean build

    - name: Run Checkstyle
      run: ./gradlew checkstyleMain checkstyleTest

  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    needs: lint

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'
      
    - name: Grant execute permission to gradlew
      run: chmod +x ./gradlew

    - name: Build Docker image
      run: docker build -t image-name .
    
    - name: Run Tests
      run: docker run image-name ./gradlew test